### PR TITLE
feat: ping endpoint

### PR DESCRIPTION
**Pull request by Delta18-Git**
## Which issue(s) does this PR address?
Adds a keep-alive ping endpoint for the render server to be kept alive.
## Why do we need this PR?
The render server can turn off, causing delays in demos.
## What logical changes are present in this PR?
The PR adds a new endpoint, and removes redefinition of some constants.
## How did you test the changes in this PR?
I ran it.
## Are there any breaking changes in this PR?
Nope.
## Is there some additional work to be done later that is NOT covered in this PR?
Not that I know of.

### CODE REVIEW

**Comment by Andy34G7** [comment]
Bad PR message, will reject /s

**Review by Andy34G7 — APPROVED** [review]
LGTM

**Review by Andy34G7 — APPROVED** [review]
